version = 1

[[annotations]]
path = ["tools/**"]
precedence = "closest"
comment = "tools"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0"

[[annotations]]
path = ["tests/**"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only"

[[annotations]]
path = ["src/plugins/qmltooling/**.json"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["**.prf", "**Info.plist", "**cmake.in", "src/**.in", "**.json", "**CMakeLists.txt", "**.cmake",
        ".cmake.conf", "**.yaml", "**.gradle", "src/quick/items/syncexcludes", "src/quickcontrols/qmldir",
        "**.cfg"]
comment = "build system"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [".tag", "**/.gitattributes", "**.gitignore"]
precedence = "closest"
comment = "not sure at all"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["**/snippets/**", "**/doc/images/**", "examples/**", "src/quick/doc/src/internal/*.puml",
        "src/quick/doc/src/internal/*.svg", "src/quick/doc/src/internal/*.dot"]
comment = "this must be after the build system table because example and snippets take precedence over build system"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR BSD-3-Clause"

[[annotations]]
path = ["qtdeclarative.doxy", "**.md", "README.md", ".gitmodules",
        "**/doc/**.qdocconf" ,
        "**/doc/**.qdocinc", "**/doc/**.dox"]
comment = "documentation"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

[[annotations]]
path = ["src/quickcontrols/imagine/*",
        "src/quickdialogs/quickdialogsquickimpl/images/**png",
        "src/quickdialogs/quickdialogsquickimpl/images/**svg",
        "src/quickcontrols/windows/images/*.png",
        "src/quickcontrols/universal/images/*.png",
        "src/quickdialogs/quickdialogsquickimpl/images/*.svg",
        "src/quickcontrols/material/images/*.png",
        "src/quickcontrols/material/images/*.svg",
        "src/quickcontrols/macos/images/*.png",
        "src/quickcontrols/macos/images/*.webp",
        "src/quickcontrols/ios/images/*.png",
        "src/quickcontrols/imagine/images/*.png",
        "src/quickcontrols/imagine/images/*.webp",
        "src/quickcontrols/fusion/images/*.png",
        "src/quickcontrols/fusion/images/*.svg",
        "src/quickcontrols/fluentwinui3/light/images/*.png",
        "src/quickcontrols/fluentwinui3/dark/images/*.png",
        "src/quickcontrols/fluentwinui3/icons/*.png",
        "src/quickcontrols/designer/images/*.png",
        "src/quickcontrols/basic/images/*.png",
        "src/particles/particleresources/*.png"]
comment = "controls and dialogs."
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"

[[annotations]]
path = "src/quick/doc/QtQuickDoc"
comment = "module"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"

[[annotations]]
path = ["src/quickcontrols/universal/README.md"]
precedence = "closest"
comment = "to be confirmed"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ["**.toml", "licenseRule.json"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

[[annotations]]
path = ["**/qt_attribution.json"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

[[annotations]]
path = ["**LICENSE*"]
precedence = "override"
comment = "License file."
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["examples/quick/quickshapes/weatherforecast/assets/generate.bat"]
precedence = "override"
comment = "the SPDX expression in file cannot be parsed"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd"
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR BSD-3-Clause"

[[annotations]]
path = "examples/quick/vectorimage/generate.bat"
precedence = "override"
comment = "tools. reuse cannot read it. override to avoid skipping the file"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0"
